#!/usr/bin/perl
# FetchIt
use strict;
use Data::Dumper;
use WWW::Mechanize;

my $m = WWW::Mechanize->new;
my $url = shift or die;
$m->agent_alias('Linux Mozilla');

$m->get($url) or print $m->status;
$m->quiet(1);

sub fetchMedia {
  foreach my $img($m->links) {
     if($img->url_abs =~ /.+(.+\.png|jpg|jpeg|flv|wmv|avi)$/) {
      my $filename = time.".$1";
      $m->follow_link(url =>  $img->url);
      print 'Saving ', $img->url, ' to ', $filename, "\n";
      $m->save_content($filename);
      $m->back;
    }
  }
}

fetchMedia;
